[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "ecommerce_poc.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["tests"]
addopts = [
    "--tb=short",
    "--strict-markers",
    "--disable-warnings",
    "--html=test_report.html",
    "--self-contained-html",
    "--capture=no"
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "e2e: marks tests as end-to-end tests"
]

[tool.playwright]
browser = "chromium"
headed = true
